(in-package #:calc)

(defun apply-unary-op (op stack)
  (if stack
      (cons (funcall op (car stack)) (cdr stack))
      stack))

(defun apply-binary-op (op stack)
  (if (>= (length stack) 2)
      (cons (funcall op (second stack) (car stack)) (cddr stack))
      stack))

(defun is-unary-func (s)
  (member (string-upcase s) '("SIN" "COS" "TAN" "ASIN" "ACOS" "ATAN"
                              "LOG" "LOG10" "EXP" "SQRT" "ABS" "NEG"
                              "ROUND" "FLOOR" "CEIL" "NOT" "BITNOT"
                              "HEX" "BIN" "DEC")
          :test #'string=))

(defun is-binary-op (s)
  (member (string-upcase s) '("+" "-" "*" "/" "^" "MOD" "MIN" "MAX"
                              "GCD" "LCM" "LOGAND" "LOGIOR" "LOGXOR"
                              "AND" "OR" "SHL" "SHR")
          :test #'string=))

(defun is-comparison (s)
  (member (string-upcase s) '(">" "<" "=" ">=" "<=" "!=") :test #'string=))

(defun is-stack-op (s)
  (member (string-upcase s) '("DUP" "SWAP" "DROP" "OVER" "ROT" "NIP")
          :test #'string=))

(defun is-control-op (s)
  (member (string-upcase s) '("?" "FOR" "IF" "THEN" "ELSE" "ENDIF" "WHILE" "REPEAT" "UNTIL")
          :test #'string=))

(defun make-binary-func (tok)
  (cond
    ((string= tok "+") #'+)
    ((string= tok "-") #'-)
    ((string= tok "*") #'*)
    ((string= tok "/") #'/)
    ((string= tok "^") #'expt)
    ((string-equal tok "MOD") #'mod)
    ((string-equal tok "MIN") #'min)
    ((string-equal tok "MAX") #'max)
    ((string-equal tok "GCD") #'gcd)
    ((string-equal tok "LCM") #'lcm)
    ((string-equal tok "LOGAND") #'logand)
    ((string-equal tok "LOGIOR") #'logior)
    ((string-equal tok "LOGXOR") #'logxor)
    ((string-equal tok "AND") (lambda (a b) (and a b)))
    ((string-equal tok "OR") (lambda (a b) (or a b)))
    ((string-equal tok "SHL") (lambda (a b) (ash (truncate a) b)))
    ((string-equal tok "SHR") (lambda (a b) (ash (truncate a) (- b))))))

(defun make-comparison-func (tok)
  (cond
    ((string= tok ">") (lambda (a b) (> a b)))
    ((string= tok "<") (lambda (a b) (< a b)))
    ((string= tok "=") (lambda (a b) (= a b)))
    ((string-equal tok ">=") (lambda (a b) (>= a b)))
    ((string-equal tok "<=") (lambda (a b) (<= a b)))
    ((string-equal tok "!=") (lambda (a b) (not (= a b))))))

(defun make-unary-func (tok)
  (let ((u (string-upcase tok)))
    (cond
      ((string= u "SIN") #'sin)
      ((string= u "COS") #'cos)
      ((string= u "TAN") #'tan)
      ((string= u "ASIN") #'asin)
      ((string= u "ACOS") #'acos)
      ((string= u "ATAN") #'atan)
      ((string= u "LOG") #'log)
      ((string= u "LOG10") (lambda (x) (log x 10)))
      ((string= u "EXP") #'exp)
      ((string= u "SQRT") #'sqrt)
      ((string= u "ABS") #'abs)
      ((string= u "NEG") #'-)
      ((string= u "ROUND") #'round)
      ((string= u "FLOOR") #'floor)
      ((string= u "CEIL") #'ceiling)
      ((string= u "NOT") (lambda (x) (not x)))
      ((string= u "BITNOT") (lambda (x) (lognot (truncate x))))
      ((string= u "HEX") (lambda (x) (format nil "~X" (truncate x))))
      ((string= u "BIN") (lambda (x) (format nil "~B" (truncate x))))
      ((string= u "DEC") (lambda (x)
                           (if (stringp x)
                               (parse-integer x :junk-allowed t)
                               x))))))

(defun eval-rpn (expr vars funcs)
  (let ((stack nil) (tokens (tokenize expr)))
    (dolist (tok tokens)
      (cond
        ((is-binary-op tok)
         (setf stack (apply-binary-op (make-binary-func tok) stack)))
        ((is-comparison tok)
         (setf stack (apply-binary-op (make-comparison-func tok) stack)))
        ((is-unary-func tok)
         (setf stack (apply-unary-op (make-unary-func tok) stack)))
        ((string= tok "!")
         (setf stack (apply-unary-op
                      (lambda (n)
                        (if (and (integerp n) (>= n 0))
                            (apply #'* (loop for i from 1 to n collect i))
                            0))
                      stack)))
        ((is-stack-op tok)
         (let ((u (string-upcase tok)))
           (cond
             ((string= u "DUP")
              (when stack (push (car stack) stack)))
             ((string= u "SWAP")
              (when (>= (length stack) 2)
                (setf stack (cons (second stack) (cons (car stack) (cddr stack))))))
             ((string= u "DROP")
              (when stack (setf stack (cdr stack))))
             ((string= u "OVER")
              (when (>= (length stack) 2)
                (push (second stack) stack)))
             ((string= u "ROT")
              (when (>= (length stack) 3)
                (setf stack (cons (third stack)
                                 (cons (car stack)
                                       (cons (second stack)
                                             (cdddr stack)))))))
             ((string= u "NIP")
              (when (>= (length stack) 2)
                (setf stack (cons (car stack) (cddr stack))))))))
        ((is-control-op tok)
         (cond
           ((string= tok "?")
            (when (>= (length stack) 3)
              (let ((false-val (pop stack))
                    (true-val (pop stack))
                    (condition (pop stack)))
                (push (if condition true-val false-val) stack))))
           ((string-equal tok "FOR")
            (when (>= (length stack) 3)
              (let ((func-name (string-upcase (pop stack)))
                    (end-val (pop stack))
                    (start-val (pop stack)))
                (let ((func (gethash func-name funcs)))
                  (when func
                    (let ((arg-names (getf func :args))
                          (body (getf func :body)))
                      (loop for i from start-val to end-val do
                        (when arg-names
                          (setf (gethash (first arg-names) vars) i))
                        (eval-rpn body vars funcs))))))))))
        ((or (string= tok "(") (string= tok ")"))
         nil)
        (t
         (let ((v (resolve-token tok vars)))
           (push v stack)))))
    (if stack (car stack) nil)))
