(in-package #:calc)
(defun resolve-token (token vars)
  (let ((upper (string-upcase token)))
    (cond
      ((let ((v (ignore-errors (read-from-string token))))
         (when (numberp v) v)))
      ((string= upper "PI") pi)
      ((string= upper "E") (exp 1))
      ((string= upper "GOLDEN") (/ (+ 1 (sqrt 5)) 2))
      ((string= upper "T") t)
      ((string= upper "TRUE") t)
      ((string= upper "NIL") nil)
      ((string= upper "FALSE") nil)
      ((gethash upper vars))
      (t nil))))

