(in-package #:calc)

(defun tokenize (expr)
  (let ((tokens nil) (cur "") (i 0) (len (length expr))
        (last-was-value nil) (space-seen nil))
    (flet ((flush-cur ()
             (when (> (length cur) 0)
               (push (copy-seq cur) tokens)
               (setf last-was-value
                     (or (digit-char-p (char cur 0))
                         (and (> (length cur) 1)
                              (char= (char cur 0) #\-)
                              (digit-char-p (char cur 1)))
                         (and (> (length cur) 1)
                              (char= (char cur 0) #\.))
                         (and (> (length cur) 1)
                              (char= (char cur 0) #\")
                              (char= (char cur (1- (length cur))) #\"))
                         (string-equal cur "T")
                         (string-equal cur "TRUE")
                         (string-equal cur "NIL")
                         (string-equal cur "FALSE")))
               (setf cur ""))))
      (loop while (< i len) do
        (let ((ch (char expr i)))
          (cond
            ;; String literals
            ((char= ch #\")
             (flush-cur)
             (let ((start i))
               (incf i)
               (loop while (< i len) do
                 (when (char= (char expr i) #\")
                   (return))
                 (when (char= (char expr i) #\\)
                   (incf i))
                 (incf i))
               (when (< i len)
                 (incf i))
               (push (subseq expr start i) tokens)
               (setf last-was-value t)
               (setf space-seen nil)))
            ;; Array literals [ ... ]
            ((char= ch #\[)
             (flush-cur)
             (let ((depth 1) (start i))
               (incf i)
               (loop while (and (< i len) (> depth 0)) do
                 (cond
                   ((char= (char expr i) #\[) (incf depth))
                   ((char= (char expr i) #\]) (decf depth)))
                 (incf i))
               (push (subseq expr start i) tokens)
               (setf last-was-value t)
               (setf space-seen nil)))
            ;; Whitespace: flush and mark space seen
            ((or (char= ch #\Space) (char= ch #\Tab) (char= ch #\Newline))
             (flush-cur)
             (setf space-seen t)
             (incf i))
            ;; Two-char operators: >=, <=, !=
            ((and (or (char= ch (char ">" 0))
                      (char= ch (char "<" 0))
                      (char= ch (char "!" 0)))
                  (< (1+ i) len)
                  (char= (char expr (1+ i)) (char "=" 0)))
             (flush-cur)
             (push (format nil "~c~c" ch (char "=" 0)) tokens)
             (setf last-was-value nil)
             (setf space-seen nil)
             (incf i 2))
            ;; Minus sign as unary: not after a value, and next is digit
            ((and (char= ch #\-)
                  (or space-seen
                      (and (not last-was-value)
                           (or (= (length cur) 0)
                               (not (or (digit-char-p (char cur 0))
                                        (and (> (length cur) 1)
                                             (char= (char cur 0) #\-)
                                             (digit-char-p (char cur 1)))
                                        (and (> (length cur) 1)
                                             (char= (char cur 0) #\.))
                                        (string-equal cur "T")
                                        (string-equal cur "TRUE")
                                        (string-equal cur "NIL")
                                        (string-equal cur "FALSE"))))))
                  (< (1+ i) len)
                  (let ((next (char expr (1+ i))))
                    (or (digit-char-p next) (char= next #\.))))
             (flush-cur)
             (setf cur (string ch))
             (setf space-seen nil)
             (incf i))
            ;; Operators: + - * / ^ ! ( ) ? = > <
            ((or (char= ch #\+) (char= ch #\-) (char= ch #\*)
                 (char= ch #\/) (char= ch #\^) (char= ch #\!)
                 (char= ch #\() (char= ch #\))
                 (char= ch #\?)
                 (char= ch (char "=" 0))
                 (char= ch (char ">" 0))
                 (char= ch (char "<" 0)))
             (if (and (> (length cur) 0)
                      (char= (char cur 0) #\M)
                      (= (length cur) 1)
                      (or (char= ch #\+) (char= ch #\-)))
                 (progn
                   (push (concatenate 'string cur (string ch)) tokens)
                   (setf last-was-value nil)
                   (setf cur "")
                   (setf space-seen nil)
                   (incf i))
                 (progn
                   (flush-cur)
                   (push (string ch) tokens)
                   (setf last-was-value nil)
                   (setf space-seen nil)
                   (incf i))))
            ;; Default: accumulate into current token
            (t
             (setf cur (concatenate 'string cur (string ch)))
             (setf space-seen nil)
             (incf i)))))
      (flush-cur))
    (nreverse tokens)))
