(in-package #:calc)

(defun tokenize (expr)
  (let ((tokens nil) (cur "") (i 0) (len (length expr)))
    (loop while (< i len) do
      (let ((ch (char expr i)))
        (cond
          ((or (char= ch #\Space) (char= ch #\Tab) (char= ch #\Newline))
           (when (> (length cur) 0)
             (push (copy-seq cur) tokens)
             (setf cur ""))
           (incf i))
          ((and (or (char= ch (char ">" 0))
                    (char= ch (char "<" 0))
                    (char= ch (char "!" 0)))
                (< (1+ i) len)
                (char= (char expr (1+ i)) (char "=" 0)))
           (when (> (length cur) 0)
             (push (copy-seq cur) tokens)
             (setf cur ""))
           (push (format nil "~c~c" ch (char "=" 0)) tokens)
           (incf i 2))
          ((or (char= ch #\+) (char= ch #\-) (char= ch #\*)
               (char= ch #\/) (char= ch #\^) (char= ch #\!)
               (char= ch #\() (char= ch #\))
               (char= ch #\?)
               (char= ch (char "=" 0))
               (char= ch (char ">" 0))
               (char= ch (char "<" 0)))
           (when (> (length cur) 0)
             (push (copy-seq cur) tokens)
             (setf cur ""))
           (push (string ch) tokens)
           (incf i))
          (t
           (setf cur (concatenate 'string cur (string ch)))
           (incf i)))))
    (when (> (length cur) 0)
      (push (copy-seq cur) tokens))
    (nreverse tokens)))
